export const MAPS = [
  "Abyssal Ambush",
  "Alpine Ridge",
  "Altar of The Horned Rat",
  "Altar of Ultimate Darkness",
  "Altar to Chaos",
  "Altdorf",
  "Altdorf Outskirts",
  "Amber Bow",
  "Amaxon Plain",
  "Ancient City of Quintex",
  "Ancient Dragon Cave",
  "Arid Pass",
  "Arnheim",
  "Ash Plains",
  "Ash River",
  "Ashen Trails",
  "Ashmouth Volcano",
  "Athel Tamarha",
  "Aymara Swamps",
  "Backwoods Path",
  "Baron's Bluff",
  "Barrier Idols",
  "Basalt Bank",
  "Basalt Ridge",
  "Bastion River",
  "Battle for Itza",
  "Battle of the Cairns",
  "Battle of the Eternal Tides",
  "Bay of Corsairs Isle",
  "Bay of Corsairs Isle (North)",
  "Bay of Corsairs Isle (South)",
  "Belly Bluff",
  "Big Butte Trap",
  "Bjornling's Gathering",
  "Black Ark",
  "Black Ark Landing",
  "Black Fire Pass",
  "Black Fortress",
  "Black Gulf Bluff",
  "Black Hammer of Hashut",
  "Black Lakes",
  "Black Mountains",
  "Blackspine Chasm",
  "Blasted Lands",
  "Bleak Coast Isle",
  "Bleak Coast Isle (North)",
  "Bleak Coast Isle (South)",
  "Bleak Dale",
  "Bleak Lands",
  "Blighted Ravine",
  "Blind Desire River",
  "Bloodfire Falls",
  "Bloodpeak",
  "Bloodpine Woods",
  "Blood River",
  "Bloodwind Keep",
  "Blue Reach River",
  "Bordeleaux Brook",
  "Bordeleaux Landing",
  "Broken Bluff",
  "Broken Leg Gully",
  "Burial Mound Of Grudsnik",
  "Butchers Grounds",
  "Cairnwoods",
  "Captain Roth's Moondial",
  "Carrion's Course",
  "Castle Drakenhof",
  "Cauldron Creek",
  "Caverns of Mourn",
  "Caverns of the Great Bat",
  "Celestial Lake",
  "Central Chaos Wastes",
  "Chaos Runeshield",
  "Chaos Wastes",
  "Chaqua",
  "Charnel Valley",
  "Chasm of Chaos",
  "Chasm of the Condor/Chasm of the Vulture",
  "Choking Pits",
  "City of Bones",
  "Claw Crossing",
  "Cliff of Beasts",
  "Coldfire Cavern",
  "Cold Mire Bog",
  "Cold Mires",
  "Compass Reach",
  "Corpse Crossing",
  "Corrupted Plains",
  "Council of Beasts",
  "Couronne",
  "Couronne's River Island",
  "Crossing the Reikland",
  "Crossing the Sea of Claws",
  "Crossroads",
  "Crumbling Cliffs",
  "Crystal Causeway",
  "Crystal Mountains",
  "Culchan Plains",
  "Cursed Marshes",
  "Da Big Butte",
  "Da Huntin' Groundz",
  "Da Stompin' Groundz",
  "Dappled Flow",
  "Dark Mouth Pass",
  "Darkened Gorge",
  "Darkened Height",
  "Darkened Run",
  "Darkland Peak",
  "Deadwood",
  "Death Pass",
  "Death Pass Deeps",
  "Derailment",
  "Desert Canyon",
  "Devastation of Ostermark",
  "Dharko Wharf",
  "Dok Karaz",
  "Doom Gate",
  "Doom Glades",
  "Doom Reach",
  "Dragon Ash Fields",
  "Dragon Fang Mount",
  "Dragon Gate",
  "Dragon River Run",
  "Dread Crossing",
  "Dushyka",
  "Duskwatch Plateau",
  "Eagle Gate",
  "Eastern Straits Isle",
  "Eastern Straits Isle (North)",
  "Eastern Straits Isle (South)",
  "Ecstasy Expanse",
  "Eilhart",
  "Empire Unfortified",
  "Empty Gut Valley",
  "Enchanted Estuary",
  "Erengrad",
  "Eschen",
  "Estalian Tomb",
  "Everale Ridge",
  "Evershale",
  "Excavation Site",
  "Fallen Gates",
  "Fall of Man",
  "False Oasis",
  "Fascination Fields",
  "Fay Grove",
  "Feasting Forest",
  "Fields of Chaos",
  "Fields of Desolation",
  "Fields of Doom",
  "Fields of Eternity",
  "Fields of Possibility",
  "Finuval Flood",
  "Firemouth Volcano",
  "Fjord's Edge",
  "Floating Chaos Island",
  "Floating Farms",
  "Forest Hill",
  "Forest of Shadows",
  "Forests Edge Walk",
  "Forests of Bone",
  "Fort Ostrosk",
  "Foundry of Bones",
  "Frail Route",
  "Frigid Cross",
  "Frolic Fields",
  "Gaean Vale",
  "Galbaraz",
  "Galleon's Cove",
  "Gates of Ekrund",
  "Ghastly Gorge",
  "Gilgalion's Rest",
  "Glacier Lake",
  "Glade of the Everqueen",
  "Gleaming Oasis",
  "Glooming Wood",
  "Gnaw Pit",
  "Golden Monolith",
  "Golden Tributes",
  "Gor Gazan",
  "Gore Gateway",
  "Gouger Gully",
  "Graveyard Pass",
  "Great Forests Edge",
  "Great Hunt Tomb",
  "Greed Grove",
  "Green River",
  "Grey Guardians",
  "Grey Mountain Stables",
  "Grey Rock Point",
  "Grim Crag",
  "Grimminhagen",
  "Grissenwald",
  "Gristle Valley",
  "Grove of Slaughter",
  "Halls of Karak Azul",
  "Har Kaldra",
  "Hel Fenn",
  "Hell Pit",
  "Hellshard Amulet",
  "Helmgart",
  "Heorot Ridge",
  "Herdstone",
  "Hidden Oasis",
  "Hidden Waystone",
  "High Pass",
  "High Peak Pass",
  "Horned Hills",
  "Howling Citadel",
  "Howling Hills",
  "Howling Rock",
  "Hungering Valley",
  "Husk Desert",
  "Hunter's Pass",
  "Ice River",
  "Ice Rock Gorge",
  "Ice Witch Mountain",
  "Ice Witch Rescue",
  "Icy Breath Bridge",
  "Iron Mine Pass",
  "Iron Mountain Pass",
  "Ironsand Desert",
  "Ironspike Gorge",
  "Isle of the Crimson Skull",
  "Jade Desert",
  "Ka-Sabar",
  "Karak Azgaraz",
  "Karak Kadrin",
  "Kelp & Koldust",
  "Khemri",
  "Kislev",
  "Kislev River",
  "Knights Run/Knights' Run",
  "Knights Viewpoint",
  "Kunlan",
  "L'Anguille",
  "Lake Incatol",
  "Lake Lava",
  "Lake of Luxury",
  "La Maisontaal Abbey",
  "Land of Spite",
  "Laurelorn Forest",
  "Leitziger Ford",
  "Limpopu River",
  "Lingering Lair",
  "Loggers Line",
  "Lord Kroak's Temple",
  "Lost Temple",
  "Lost Vault of King Lunn",
  "Lothern",
  "Lurkin' Geyserz",
  "Lyonesse Coast",
  "Manor Hill",
  "Manor Pass",
  "Marbad's Tomb",
  "Mask of Heavens",
  "Middenheim",
  "Ming Zhu",
  "Mirror Woods",
  "Misty Valley",
  "Moonlight Ridge",
  "Moorlands Trap",
  "Mortis Wastes",
  "Mortuary of Tzulaqua",
  "Mosquito Swamps",
  "Mountain of Skulls",
  "Mount Grey Hag",
  "Mount Grimfang",
  "Mouth of the Pass",
  "Mountains of Mourn",
  "Mushroom Cave",
  "Naggarond",
  "Nan-Gau",
  "Nexus of the Oak",
  "Nongchang",
  "Norden",
  "Northern Chaos Wastes",
  "Nuln",
  "Numas",
  "Oakenhammer",
  "Oakheart Forest",
  "Oasis of False Hope",
  "Obsidian Coast",
  "Obsidian Fields",
  "Obsidian Peaks",
  "Ogre Camp",
  "Ogre Haunt",
  "Old Brightstone Mine",
  "Old Corpse Hills",
  "Olden Crag",
  "Old Forest Road",
  "Old Hunt Rise",
  "Ostermark Lookout",
  "Osterwald",
  "Pack Ice Bay",
  "Parched Pass",
  "Parravon",
  "Passages of the Asrai",
  "Path of Provocation",
  "Pathway to Darkness",
  "Peak Hunger",
  "Peak Pass",
  "Peasants Pasture",
  "Peasants Ploy",
  "Persistent Peak",
  "Pestilent Plateau",
  "Pillar Of Bone",
  "Pits of Zardok",
  "Plague Path",
  "Plain of Spiders",
  "Plain of the Darklands",
  "Plains of the Dead",
  "Plains of the Patriarch",
  "Plaque of Sotek",
  "Plateau of the Dead",
  "Pleasures Reach",
  "Praag",
  "Quenelles",
  "Qu'ittax",
  "Rackdo Ridge",
  "Ravenous Range",
  "Red Desert",
  "Red Dust Route",
  "Red Fortress",
  "Reikland Homestead",
  "Reikwald Forest",
  "Retired Ridge",
  "River Amaxon",
  "River Qurverza",
  "River Vilu",
  "Road to Talabheim",
  "Roq'Ato Pools",
  "Ruins of Enduil",
  "Sabre Mountain",
  "Sartosa",
  "Schwartzhafen",
  "Scorched Valley",
  "Scrag Hole",
  "Sea of Chaos Isle (East)",
  "Sea of Chaos Isle (North)",
  "Sea of Chaos Isle (South)",
  "Serpet Jetty",
  "Shadow Forest",
  "Shadow Mountain",
  "Shadow Realm",
  "Shadow Wood",
  "Shady Oak",
  "Shagrath Strand",
  "Shang-Yang",
  "Shell Mountain",
  "Shifting Isles",
  "Shifting Isles Desert",
  "Shifting Isles Snowy",
  "Shimmersward",
  "Shrine of Asuryan",
  "Shrine of Ill Omen",
  "Shrine of Khaine",
  "Sickening Swamp",
  "Skjold",
  "Skullcap Mount",
  "Slann Gold",
  "Smothered Skies",
  "Southern Chaos Wastes",
  "Spawning Pools",
  "Spice Dunes",
  "Spine Path",
  "Spite Reach",
  "Spite Reach Pass",
  "Star of Avelorn",
  "Stinkin' Geyserz",
  "Stir River",
  "Storm Daemon",
  "Sulphur River",
  "Summersong",
  "Sundered Strand",
  "Swamp of Terror",
  "Sword of Torgald",
  "Tarrantula Coast Isle",
  "Tempest Plains",
  "Temple of Huanchi",
  "Temple of Skulls",
  "Temple of Ursun",
  "Terracotta Walk",
  "The Abyss",
  "The Altar of Battle",
  "The Arid Shrine",
  "The Ashenhall",
  "The Ashen Riverbed",
  "The Ash Plains",
  "The Backwoods",
  "The Barren Plains",
  "The Bitter Dunes",
  "The Black Chasm",
  "The Black Deeps",
  "The Black Flood",
  "The Black Forests",
  "The Black Pyramid",
  "The Black Tower of Arkhan",
  "The Blasted Wastes",
  "The Bleeding Spire",
  "The Blood Fen",
  "The Blood Swamps",
  "The Brass Citadel",
  "The Brass Glacier",
  "The Broken Land",
  "The Chill Flow",
  "The Clouded Lane",
  "The Corrupted Hallway",
  "The Cracked Land",
  "The Crack of Karkan",
  "The Cursed Jungle",
  "The Dammed Lady",
  "The Dancing Hills",
  "The Dark Crater",
  "The Dead Shore",
  "The Dead Wood",
  "The Declining Path",
  "The Deep Mines",
  "The Desert's Bounty",
  "The Desert's Run",
  "The Dragon Isles",
  "The Dragons Den",
  "The Dry Plains",
  "The Ember Glades",
  "The Essence of Chaos",
  "The Eye in the North",
  "The Eyrie",
  "The Fey Fork",
  "The Flats of Frenzy",
  "The Flats of Kislev",
  "The Forbidden Citadel",
  "The Forge of Souls",
  "The Fractal Labyrinth",
  "The Frozen Falls",
  "The Galleon's Graveyard",
  "The Gates of Zharr",
  "The Golden Colossus",
  "The Greased Expanse",
  "The Great Bulwark",
  "The Great Drill of Hashut",
  "The Great Forest",
  "The Green Abyss",
  "The Gross Green",
  "The Great Gulley",
  "The Grim Gambit",
  "The Hazed Hallway",
  "The Heart of Darkness",
  "The Heart of the Dark",
  "The Hidden Lady",
  "The Hunting Fields",
  "The Impossible Fortress",
  "The Isle of the Dead",
  "The Knights Demise",
  "The Land of Lust",
  "The Lost Crater",
  "The Lost Idols",
  "The Lost Vault",
  "The Mansion of the Plaguelord",
  "The Marthenil Archipelago",
  "The Maruka Isles",
  "The Midden Crossing",
  "The Moonbow",
  "The Moondial",
  "The Moorlands Route",
  "The Night Glens",
  "The Northern Threat",
  "The Oak of Ages",
  "The Obsidian Path",
  "The Ogham Shard",
  "The Old Bastille",
  "The Olden Pass",
  "The Old Peak",
  "The Palace of Slaanesh",
  "The Path to Kunlan",
  "The Path to Nuln",
  "The Perilous Path",
  "The Pestilent Path",
  "The Pitch Flow",
  "The Raining Rocks",
  "The Red River",
  "The Reeking Mire",
  "The Reik Marsh",
  "The Reikland Estates",
  "The Road of Ruin",
  "The Run of Blood",
  "The Sea of Dreams",
  "The Shifting Monolith",
  "The Silver Plains",
  "The Silver Spire",
  "The Sky Monolith",
  "The Slag Strand",
  "The Strip Mines",
  "The Suffering Lands",
  "The Summerlands",
  "The Tarred Terrace",
  "The Tickling Tundra",
  "The Tortured Ashes",
  "The Tourney Grounds",
  "The Tourney Trap",
  "The Tower Khrakk",
  "The Truth Plain",
  "The Twisted Glade",
  "The Underway",
  "The Vale of Nightmares",
  "The Void of Hel Fenn",
  "The Vomit Fields",
  "The Wasteland",
  "The Whispering Wood",
  "The Wildfires",
  "The Writhing Fortress",
  "Thieves' Hideout",
  "Thundering Falls",
  "Todtheim",
  "Tomb of the Shifting Sands",
  "Toothgrass Hill",
  "Tor Gard",
  "Tor Yvresse (Decrepit)",
  "Tor Yvresse (Fortified)",
  "Tor Yvresse (Rebuilding)",
  "Tower of Grief",
  "Tower of Hoeth",
  "Troll Country",
  "Troll Run",
  "Turtle Fields",
  "Valley of Thieves",
  "Vaul's Anvil",
  "Volcanic Channels",
  "Volcanic Stream",
  "Volksgrad",
  "Volksgrad Overlook",
  "Vulture Ridge",
  "Wailing Abyss",
  "Waldenhof",
  "Walk on the Wildfire",
  "Wamp Rat Gulch",
  "Warpblade Tunnels",
  "Warp-Shard Caverns",
  "Warpstone Crater",
  "Warpstone Mine",
  "Wastes of Khorne",
  "Wastes of Nurgle",
  "Wastes of Slaanesh",
  "Wastes of Tzeentch",
  "Watcher Hills",
  "Watcher Ruins",
  "Watcher's Peak",
  "Waylaid Garrison",
  "Wei-Jin",
  "Weng Chang",
  "Wildwood Prison",
  "Wind Ripple",
  "Winter Pyre",
  "Wintertooth Crown",
  "Witch Grove",
  "Witchwood Glade",
  "Witchwood Hollow",
  "Witchwood River",
  "Woodland Ravine",
  "Wyvern Cliffz",
  "Wyvern Lake",
  "Xing Po",
  "Xing-Po Floodplains",
  "Xuhua Lake",
  "Yhetee Peak",
  "Zharr-Naggrund",
  "Zhufbar",
  "Zoishenk",
  "Altar of Hashut",
  "Altar of the Champion",
  "Altdorf Farmlands",
  "Aracknarock Lair",
  "Arbiter's Grounds",
  "Battered Bluff",
  "Bleakspire Labor Camp",
  "Bray Valley",
  "Chateau de Roquefort",
  "Clash of Chaos",
  "Coedill's Mistwood",
  "Crater of Decay",
  "Creeping Swamp",
  "Crystal Lake",
  "Decrepit Moor",
  "Dried Floodplain",
  "Dunes of Khaine",
  "Dunes of Setep",
  "Dustbowl",
  "Dusted Steppe",
  "Eastern Isle Colony",
  "Edge of the Darkwood",
  "Geothermal Crevice",
  "Geyser Bluff",
  "Glinty Toof's Crag",
  "Graveyard of Altdorf",
  "Halls of Karag Dum",
  "Hashut's Oilfields",
  "Haunted Vale",
  "Hell Pit Depths",
  "Imperial Ambush",
  "Imperial Road",
  "Isle of Forgotten Kings",
  "Jade Tomb",
  "Khsar's Cursed Oasis",
  "Lost Isles of Culchan",
  "Lost Temple of Sotek",
  "Lustrian Narrows",
  "Needlemyst Isle",
  "Nehekharan Wastes",
  "Norscan Rise",
  "Nuln Outskirts",
  "Oakenshield",
  "Oasis of Zedri",
  "Otsuchi Castle",
  "Pit of the Everchosen",
  "Proving Grounds",
  "Rifts at the World's Edge",
  "Road to Vaul's Anvil",
  "Ruins of Arrogance",
  "Sacred Cenote of Chaqua",
  "Shambling Bog",
  "Skjalandir's Cave",
  "Stone'enge",
  "Sunken Mire",
  "Talebheim Crater",
  "Temple of Usirian",
  "Terracotta Graveyard",
  "The Blood Grove",
  "The Changer's Madhouse",
  "The Crucible",
  "The Hag's Conclave",
  "The Mountain of Truth",
  "The Valley of Lies",
  "Twilight Forest",
  "Urgut's Stompin Groundz",
  "Womb of Sorrow",
  "Zharr-Naggrund Rebellion",
];
